# Generated by Django 5.2.4 on 2026-06-15 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('authors', models.JSONField(blank=True, default=list)),
                ('book_metadata', models.JSONField(blank=True, null=True)),
                ('videos', models.JSONField(blank=True, null=True)),
                ('apocrypha', models.JSONField(blank=True, null=True)),
                ('source_commit', models.CharField(blank=True, max_length=64)),
                ('built_at', models.CharField(blank=True, max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120)),
                ('title', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hash', models.CharField(blank=True, default='', max_length=100)),
                ('appendix', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='book.book')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('book', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120)),
                ('title', models.CharField(max_length=300)),
                ('order', models.PositiveIntegerField(default=0)),
                ('hash', models.CharField(blank=True, default='', max_length=100)),
                ('html', models.TextField(blank=True)),
                ('online_resources', models.TextField(blank=True)),
                ('online_only', models.BooleanField(default=False)),
                ('anchors', models.JSONField(blank=True, default=list)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='book.book')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='book.chapter')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
