# Generated by Django 5.2.15 on 2026-06-24 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parody_web', '0007_book_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='plain',
            field=models.TextField(blank=True, default=''),
        ),
    ]
