# Generated by Django 5.2.15 on 2026-08-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parody_web', '0008_section_plain'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='has_solutions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='section',
            name='problems',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='section',
            name='solutions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='section',
            name='hash',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
    ]
