# Generated by Django 5.2.15 on 2026-08-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parody_web', '0009_section_solutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='print_pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='print_pdf',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='print_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='section',
            name='print_pages',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
