# Generated by Django 5.2.15 on 2026-08-16 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parody_web', '0010_print_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPrintVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha256', models.CharField(max_length=64)),
                ('filename', models.CharField(max_length=200)),
                ('page_count', models.PositiveIntegerField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='print_versions', to='parody_web.book')),
            ],
            options={
                'ordering': ['-first_seen'],
                'indexes': [models.Index(fields=['book', 'sha256'], name='parody_web__book_id_ac9cb0_idx')],
                'unique_together': {('book', 'sha256')},
            },
        ),
    ]
