# Generated by Django 5.2.15 on 2026-08-19 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parody_web', '0011_bookprintversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_slug', models.CharField(max_length=100)),
                ('edition_id', models.CharField(blank=True, default='', max_length=50)),
                ('section_key', models.CharField(max_length=200)),
                ('table_id', models.CharField(max_length=120)),
                ('row', models.PositiveIntegerField()),
                ('column', models.CharField(max_length=64)),
                ('value', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parody_table_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['table_id', 'row', 'column'],
                'indexes': [models.Index(fields=['user', 'book_slug', 'section_key'], name='parody_web__user_id_103687_idx')],
                'unique_together': {('user', 'book_slug', 'edition_id', 'section_key', 'table_id', 'row', 'column')},
            },
        ),
    ]
