# Generated by Django 5.2.15 on 2026-08-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parody_web', '0012_tableentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='draft',
            field=models.BooleanField(default=False),
        ),
    ]
