# Generated by Django 5.2.15 on 2026-08-16 09:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InkLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_slug', models.CharField(max_length=100)),
                ('edition_id', models.CharField(blank=True, default='', max_length=50)),
                ('section_key', models.CharField(max_length=200)),
                ('slice_key', models.CharField(max_length=64)),
                ('book_sha256', models.CharField(max_length=64)),
                ('pages', models.JSONField()),
                ('strokes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parody_ink_layers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'book_slug', 'section_key'], name='parody_web__user_id_884f58_idx'), models.Index(fields=['book_sha256'], name='parody_web__book_sh_f05faf_idx')],
                'unique_together': {('user', 'book_slug', 'edition_id', 'section_key', 'slice_key')},
            },
        ),
    ]
