# Generated by Django 5.2.15 on 2026-08-17 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parody_web_annotate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inklayer',
            name='pads',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
