# Generated by Django 5.2.15 on 2026-08-17 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadAlongTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_slug', models.CharField(max_length=100)),
                ('edition_id', models.CharField(blank=True, default='', max_length=50)),
                ('section_key', models.CharField(max_length=200)),
                ('slice_key', models.CharField(max_length=64)),
                ('voice_id', models.CharField(max_length=50)),
                ('engine', models.CharField(default='neural', max_length=20)),
                ('audio_name', models.CharField(max_length=200)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('words', models.JSONField(blank=True, default=list)),
                ('clozes', models.JSONField(blank=True, default=list)),
                ('pages', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['book_slug', 'section_key'], name='parody_web__book_sl_981392_idx'), models.Index(fields=['slice_key'], name='parody_web__slice_k_e0b9f9_idx')],
                'unique_together': {('book_slug', 'edition_id', 'section_key', 'slice_key', 'voice_id')},
            },
        ),
    ]
