# Generated by Django 5.2.15 on 2026-08-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parody_web_readaloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='readalongtrack',
            name='regions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
