# Generated by Django 5.2.15 on 2026-08-18 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parody_web_readaloud', '0002_readalongtrack_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='readalongtrack',
            name='text_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='readalongtrack',
            name='token_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='readalongtrack',
            index=models.Index(fields=['text_key'], name='parody_web__text_ke_a95c5c_idx'),
        ),
    ]
